name: chemprop

channels:
  - rdkit

dependencies:
  - pip>=20.0.0
  - python=3.6
  - rdkit=2020.03.3.0
  - scipy>=1.4.1
  - scikit-learn>=0.22.2.post1
  - pip:
      - qmdesc
      - tensorflow==2.0.0